#!/usr/bin/env bash
set -e

echo "Installing SSH keys from bucket..."
gsutil cp gs://shm-secrets/id_rsa ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
gsutil cp gs://shm-secrets/id_rsa.pub ~/.ssh/id_rsa.pub

echo "Setting up \$PATH..."
echo 'export CUDA_HOME=/usr/local/cuda' >> ~/.bashrc
echo 'export PATH=$PATH:$CUDA_HOME/bin' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
source ~/.bashrc

git config --global user.email "justin@dujardinconsulting.com"
git config --global user.name "Justin DuJardin"

echo "Cloning mz..."
git clone git@github.com:justindujardin/mathzero.git

echo "Installing requirements..."
cd mathzero
sudo /etc/pyenv/bin/pip install -r requirements.txt

echo "Done."