#!/usr/bin/env bash
set -e

echo "Configuring nVidia GPU"
sudo nvidia-smi -pm 1

echo "Create virtualenv at /etc/pyenv/"
sudo mkdir -p /etc/pyenv/
sudo python3.6 -m venv /etc/pyenv/

echo "Installing Tensorflow GPU"
sudo /etc/pyenv/bin/pip install tensorflow-gpu

echo "Installing Keras and PyTorch"
sudo /etc/pyenv/bin/pip install keras torch torch-vision

echo "Done."